version: '3.7'
services:
  tradepros-api:
    build: registry/tradepros-api:vx.y.z
    environment: 
      - FINNHUB_URL=${FINNHUB_URL}
      - ALPHAVANTAGE_URL=${ALPHAVANTAGE_URL}
      - AWS_URL=${AWS_URL}
      - AWS_KEY=${AWS_KEY}
      - FIREBASE_KEY=${FIREBASE_KEY}
      - FINNHUB_KEY=${FINNHUB_KEY}
      - ALPHAVANTAGE_KEY=${ALPHAVANTAGE_KEY}
      - BASE_URL=${BASE_URL}
      - MARKETDATA_URL=${MARKETDATA_URL}
      - MARKETDATA_TOKEN=${MARKETDATA_TOKEN}
      ports:
        - "1323:1323"

  caddy:
    build: registry/tradepros-ui:vx.y.z
    restart: unless-stopped
    environment:
      - VITE_FIREBASE_APIKEY=${VITE_FIREBASE_APIKEY}
      - VITE_FIREBASE_AUTHDOMAIN=${VITE_FIREBASE_AUTHDOMAIN}
      - VITE_FIREBASE_PROJECTID=${VITE_FIREBASE_PROJECTID}
      - VITE_FIREBASE_STORAGEBUCKET=${VITE_FIREBASE_STORAGEBUCKET}
      - VITE_FIREBASE_MESSAGINGSENDERID=${VITE_FIREBASE_MESSAGINGSENDERID}
      - VITE_FIREBASE_APPID=${VITE_FIREBASE_APPID}
      - VITE_FIREBASE_MEASUREMENTID=${VITE_FIREBASE_MEASUREMENTID}
      - VITE_BASE_URL=${VITE_BASE_URL}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tradepros-api