# Execute the file in the lambda_package directory

FROM public.ecr.aws/lambda/python:3.11

# Copy dependencies file
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Copy function code
COPY inference.py ${LAMBDA_TASK_ROOT}

# Copy other modules
COPY data_handler.py ${LAMBDA_TASK_ROOT}
COPY model_manager.py ${LAMBDA_TASK_ROOT}
COPY models.py ${LAMBDA_TASK_ROOT}
COPY model_checkpoints ${LAMBDA_TASK_ROOT}/model_checkpoints

# Install all dependencies
RUN pip install -r requirements.txt

# Install PyTorch for Linux (CPU only)
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu 

# Set the CMD to your handler
# Note: "{file_name}.{function to run in AWS lambda}"
CMD [ "inference.get_model_prediction" ]